[package]
name = "web_server"
version = "0.1.0"
authors = ["Geovani da Silva Júnior <geovanij3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
